# Misskey runtime config for local Docker testing.

url: http://localhost:3000/
port: 3000
setupPassword: "host"

db:
  host: db
  port: 5432
  db: misskey
  user: postgres
  pass: postgres

dbReplications: false

redis:
  host: redis
  port: 6379

id: 'aidx'

proxyBypassHosts:
  - api.deepl.com
  - api-free.deepl.com
  - www.recaptcha.net
  - hcaptcha.com
  - challenges.cloudflare.com
